source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
plugin 'slather'

target 'NTimer', :exclusive => true do
  pod "NHTimer", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NHTimer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
