# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
rvm: 1.9.3
podfile: Example/Podfile
before_install:
- gem install cocoapods slather activesupport
- pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- slather setup Example/NTimer.xcodeproj
- set -o pipefail && xcodebuild test -workspace Example/NTimer.xcworkspace -scheme NTimer-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint --quick
after_success: 
- slather
